### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by zpwebbear** [makeupyourmind/Hotel-booking#1]
1. Нигде в документации ни в консоли не указано на каком порту приложение. 
2. На Get / висит ответ http://i.imgur.com/mkcI3nf.png такого быть не должно.
3. Захардкожены доступы к базе данных http://i.imgur.com/3A1D23o.png
4. Весь проект одним коммитом - http://i.imgur.com/n6grsZN.png
5. dist в гите - http://i.imgur.com/op2ECVo.png - содержимое данной директории билдится при npm start. Эти директори  нужно ложить в гитигнор
6. Урл не соответствует заданию http://i.imgur.com/ub2DEH7.png 

Дальше проверять не буду, пока не основательно всё не поправишь

**Comment by makeupyourmind** [comment]
1.Указал в документации на каком порту прослушивается api - 3000
2. На get убрал ответ 
3. Чтобы изменить коннект к базе данных нужно зайти в папку src -> config -> keys.js
4. Приму к сведению, в дальнейшем исправлюсь
5. Добавил dist в gitignore
6. Изменил url

**Comment by zpwebbear** [comment]
1. При попытке повторно создать того же юзера https://boards.qbex.io/?name=viktor#/board/77/card/4391 не правильный код ошибки. То же самое при успешной авторизации
2. keys.js http://i.imgur.com/xFLhfXF.png должен быть в гитигноре, в гите должен лежать keys.example.js в котором перечислены все поля которые необходимы для того чтобы запустилось приложение. Я  дописал свои креды и теперь мне  гит посвечивает что это нужно закоммитить
3. Для того чтобы создать тикет в холле мне нужно указать user_id, а мне данное значение нигде не возвращается. Естественно далее проверять я не могу. Нужно реализовать возврат user_id при аутентификации

**Comment by makeupyourmind** [comment]
1. Изменил код на 400 
2. keys.js добавил в гитигноре, вместо этого файла будет лежать файл keys.example.js, в котором будут поля которые необходимы для запуска приложения
3.Вернул user_id после аутентификации

**Comment by zpwebbear** [comment]
1. Если в енпоинт tickets/:from/:to отправить данные в которых from будет больше чем to то должна возвращаться ошибка валидации.
2. При удалении холла(ов), нужно удалять и прикреплённыек нему тикеты.

**Comment by makeupyourmind** [comment]
1.Исправил - будет приходить ошибка 422
2. Сделано

Реализовал сиды - 1 админ, 1 юзен

**Comment by zpwebbear** [comment]
1. Добавить кастомную валидацию для GET /tickets/:from/:to
2. Добавить access-control - определение ролей и разрешений (roles & permissions) для каждого запроса
3. В директории  db keys.example

**Comment by makeupyourmind** [comment]
1.Добавил кастомную валидацию
2.Под вопросом, никак не выходит реализовать
3.Сделано

**Comment by zpwebbear** [comment]
Отлично!
